const SET_VARIANTS = 'SET_VARIANTS'
const SOLVE_VARIANT= 'SOLVE_VARIANT'
const SOLVE_VARIANTS= 'SOLVE_VARIANTS'
const CLOSE_MODAL= 'CLOSE_MODAL'
const STEP_VARIANT= 'STEP_VARIANT'


export default{
    SET_VARIANTS,
    SOLVE_VARIANT,
    SOLVE_VARIANTS,
    CLOSE_MODAL,
    STEP_VARIANT



    

}